# Generated by Django 4.2.5 on 2023-09-10 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="user",
            new_name="author",
        ),
    ]
